language: node_js
node_js:
  - "4.4.5"
services:
  - mongodb
before_script:
  - npm install -g gulp
  - sleep 15
install:
  - npm install -g bower
  - npm install
  - bower install --force-latest
script:
  - "npm test"
notifications:
  slack: carecenter-nonprofit:kYlXXtv0DOrnIVZhkNzKevsN